CREATE TABLE PHYSICIANS (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    contact_number VARCHAR(20),
    secondary_contact_number VARCHAR(20),
    email VARCHAR(255),
    specialization VARCHAR(255),
    license_number VARCHAR(50),
    hospital VARCHAR(255),
    office_address VARCHAR(255),
    years_of_experience INT,
    status ENUM('ACTIVE', 'INACTIVE') DEFAULT 'ACTIVE',
    created_by VARCHAR(255),
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_modified_by VARCHAR(255),
    last_modified_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    row_version INT DEFAULT 1
);

CREATE TABLE PATIENTS (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    medical_record_number VARCHAR(50) UNIQUE NOT NULL,
    start_of_care_date DATE,
    status VARCHAR(50),
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    sex VARCHAR(10),
    birth_date DATE,
    marital_status VARCHAR(50),
    address VARCHAR(255),
    city VARCHAR(255),
    state VARCHAR(255),
    county VARCHAR(255),
    zip_code VARCHAR(20),
    email VARCHAR(255),
    mobile VARCHAR(20),
    referrer_name VARCHAR(255),
    referrer_email VARCHAR(255),
    referrer_mobile VARCHAR(20),
    primary_diagnosis VARCHAR(255),
    second_diagnosis VARCHAR(255),
    third_diagnosis VARCHAR(255),
    physician_id BIGINT,
    created_by VARCHAR(255),
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_modified_by VARCHAR(255),
    last_modified_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    row_version INT DEFAULT 1,
    FOREIGN KEY (physician_id) REFERENCES physicians(id)
);